export const USER_DATA = ['Portail 360', 'Jenkins', 'Artifactory/Xray', 'Release', 'Ansible Tower', 'ArgoCD', 'Infra as Code'];

export const DROPDOWN_OPTIONS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

export const TABLE_DATA = [
    { id: 1, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 2, country: 'Kuwait', offer: 'CD', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 3, country: 'United States', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 4, country: 'United States', offer: 'Storage', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 5, country: 'United Kingdom', offer: 'CD', team: 'Middlebury College', appId: 'AP19472' },
    { id: 6, country: 'United Kingdom', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 7, country: 'Turkey', offer: 'Storage', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 8, country: 'Jordan', offer: 'CD', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 9, country: 'United States', offer: 'Storage', team: 'Middlesbrough College', appId: 'AP19472' },
    { id: 10, country: 'United States', offer: 'Storage', team: 'Middlesex University - London', appId: 'AP19472' },
    { id: 11, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 12, country: 'Kuwait', offer: 'CD', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 13, country: 'United States', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 14, country: 'United States', offer: 'Storage', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 15, country: 'United Kingdom', offer: 'CD', team: 'Middlebury College', appId: 'AP19472' },
    { id: 16, country: 'United Kingdom', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 17, country: 'Turkey', offer: 'Storage', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 18, country: 'Jordan', offer: 'CD', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 19, country: 'United States', offer: 'Storage', team: 'Middlesbrough College', appId: 'AP19472' },
    { id: 20, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 21, country: 'United States', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 22, country: 'Kuwait', offer: 'CD', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 23, country: 'United States', offer: 'Storage', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 24, country: 'United States', offer: 'Storage', team: 'Global-view', appId: 'AP19472' },
    { id: 25, country: 'United Kingdom', offer: 'CD', team: 'Middlesex University - London', appId: 'AP19472' },
    { id: 26, country: 'United Kingdom', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 27, country: 'Turkey', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 28, country: 'Jordan', offer: 'CD', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 29, country: 'United States', offer: 'Storage', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 30, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 31, country: 'United States', offer: 'Storage', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 32, country: 'Kuwait', offer: 'CD', team: 'Global-view', appId: 'AP19472' },
    { id: 33, country: 'United States', offer: 'Storage', team: 'Middlesex University - London', appId: 'AP19472' },
    { id: 34, country: 'United States', offer: 'Storage', team: 'Middlesbrough College', appId: 'AP19472' },
    { id: 35, country: 'United Kingdom', offer: 'CD', team: 'Middlebury College', appId: 'AP19472' },
    { id: 36, country: 'United Kingdom', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 37, country: 'Turkey', offer: 'Storage', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 38, country: 'Jordan', offer: 'CD', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 39, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 40, country: 'United States', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 41, country: 'United States', offer: 'Storage', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 42, country: 'Kuwait', offer: 'CD', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 43, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 44, country: 'United States', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 45, country: 'United Kingdom', offer: 'CD', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 46, country: 'United Kingdom', offer: 'Storage', team: 'Middle Tennessee State University', appId: 'AP19472' },
    { id: 47, country: 'Turkey', offer: 'Storage', team: 'Middlesbrough College', appId: 'AP19472' },
    { id: 48, country: 'Jordan', offer: 'CD', team: 'Middlebury College', appId: 'AP19472' },
    { id: 49, country: 'United States', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 50, country: 'United States', offer: 'Storage', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 51, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 52, country: 'Kuwait', offer: 'CD', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 53, country: 'United States', offer: 'Storage', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 54, country: 'United States', offer: 'Storage', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 55, country: 'United Kingdom', offer: 'CD', team: 'Middlesex University - London', appId: 'AP19472' },
    { id: 56, country: 'United Kingdom', offer: 'Storage', team: 'Middlesbrough College', appId: 'AP19472' },
    { id: 57, country: 'Turkey', offer: 'Storage', team: 'Global-view', appId: 'AP19472' },
    { id: 58, country: 'Jordan', offer: 'CD', team: 'Generator', appId: 'AP19472' },
    { id: 59, country: 'United States', offer: 'Storage', team: 'Middle Tennessee State University', appId: 'AP19472' },
    { id: 60, country: 'United States', offer: 'Storage', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 61, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 62, country: 'Kuwait', offer: 'CD', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 63, country: 'United States', offer: 'Storage', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 64, country: 'United States', offer: 'Storage', team: 'Middlesbrough College', appId: 'AP19472' },
    { id: 65, country: 'United Kingdom', offer: 'CD', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 66, country: 'United Kingdom', offer: 'Storage', team: 'Global-view', appId: 'AP19472' },
    { id: 67, country: 'Turkey', offer: 'Storage', team: 'Global-view', appId: 'AP19472' },
    { id: 68, country: 'Jordan', offer: 'CD', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 69, country: 'United States', offer: 'Storage', team: 'Middlesbrough College', appId: 'AP19472' },
    { id: 70, country: 'United States', offer: 'Storage', team: 'Middlesex University - London', appId: 'AP19472' },
    { id: 71, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 72, country: 'Kuwait', offer: 'CD', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 73, country: 'United States', offer: 'Storage', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 74, country: 'United States', offer: 'Storage', team: 'Middle East Technical University', appId: 'AP19472' },
    { id: 75, country: 'United Kingdom', offer: 'CD', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 76, country: 'United Kingdom', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 77, country: 'Turkey', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 78, country: 'Jordan', offer: 'CD', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 79, country: 'United States', offer: 'Storage', team: 'Middlesbrough College', appId: 'AP19472' },
    { id: 80, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 81, country: 'United States', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 82, country: 'Kuwait', offer: 'CD', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 83, country: 'United States', offer: 'Storage', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 84, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },
    { id: 85, country: 'United Kingdom', offer: 'CD', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 86, country: 'United Kingdom', offer: 'Storage', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 87, country: 'Turkey', offer: 'Storage', team: 'Middle East Technical University', appId: 'AP19472' },
    { id: 88, country: 'Jordan', offer: 'CD', team: 'Middlesex University - London', appId: 'AP19472' },
    { id: 89, country: 'United States', offer: 'Storage', team: 'Middle East University', appId: 'AP19472' },
    { id: 90, country: 'United States', offer: 'Storage', team: 'Middlesex University - London', appId: 'AP19472' },
    { id: 91, country: 'United States', offer: 'Storage', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 92, country: 'Kuwait', offer: 'CD', team: 'Middle East University', appId: 'AP19472' },
    { id: 93, country: 'United States', offer: 'Storage', team: 'Generator', appId: 'AP19472' },
    { id: 94, country: 'United States', offer: 'Storage', team: 'Middlesbrough College', appId: 'AP19472' },
    { id: 95, country: 'United Kingdom', offer: 'CD', team: 'Middlesex County College', appId: 'AP19472' },
    { id: 96, country: 'United Kingdom', offer: 'Storage', team: 'Middle East University', appId: 'AP19472' },
    { id: 97, country: 'Turkey', offer: 'Storage', team: 'Middle East Technical University', appId: 'AP19472' },
    { id: 98, country: 'Jordan', offer: 'CD', team: 'Middlesex Community College', appId: 'AP19472' },
    { id: 99, country: 'United States', offer: 'Storage', team: 'American University of Middle East', appId: 'AP19472' },
    { id: 100, country: 'United States', offer: 'Storage', team: 'Middlebury College', appId: 'AP19472' },

];